FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 go build -mod=vendor -o /out/loadgen ./cmd/loadgen

FROM alpine:latest
WORKDIR /app
COPY --from=builder /out/loadgen .
ENTRYPOINT ["./loadgen"]
